### ISSUE TITLE
questions about the codes

### ISSUE THREAD

**Issue by yzf-code** [yueyu1030/SumGNN#3]
1. The TWOSIDES source link maybe wrong? Probably this one. http://snap.stanford.edu/biodata/datasets/10017/10017-ChChSe-Decagon.html
2. In the BioSNAP dataset you have processed,including train.txt, test.txt, dev.txt and relations2hop.txt, I only found the biomedical entities(drug, protein,gene) number given in digital form.What's the correspondence between these biomedical entities numbers and real entities? You only give the correspondence about drugbank dataset.

**Comment by yueyu1030** [comment]
Thanks for your suggestion! The mapping file can be found at https://drive.google.com/file/d/1C3ZF77QvdzI3eL9sjLkBr3aytzET4JGj/view?usp=sharing.
