### ISSUE TITLE
缩小数据集

### ISSUE THREAD

**Issue by Dunant5** [yueyu1030/SumGNN#5]
请问有什么方法能缩小dataset和KG的规模吗
在个人电脑上需要花很长的时间提取子图
@yueyu1030 @kexinhuang12345

**Comment by yueyu1030** [comment]
Wrt. reducing the size for KG:
1) Currently we use KG nodes from the 2-hop neighborhood of the KG. You can reduce the size of the hop during sampling.
2) You can try to remove some specific types of nodes in the KG. (some of them might be irrelevant)

**Comment by Dunant5** [comment]
Thanks.
